In [3]:
import numpy as np


image = np.array([
    [1,1,1,0,0],
    [0,1,1,1,0],
    [0,0,1,1,1],
    [0,0,1,1,0],
    [0,1,1,0,0]
])

convolution_kernel = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])

print(image)
print(convolution_kernel)

[[1 1 1 0 0]
 [0 1 1 1 0]
 [0 0 1 1 1]
 [0 0 1 1 0]
 [0 1 1 0 0]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


In [67]:
possibleSegments = [(0,3),(1,4),(2,5)]
convolvedFeatures = []

for i in range(3):
    for j in range(3):      
        imagePart = image[possibleSegments[i][0]: possibleSegments[i][1], possibleSegments[j][0]: possibleSegments[j][1]]
        convolvedFeatures.append(np.sum(imagePart * convolution_kernel))


outputFeatureMapSize = (5 - 3) // 1 + 1     
outputFeatureMap = np.array(convolvedFeatures).reshape((outputFeatureMapSize, outputFeatureMapSize))

print(outputFeatureMap)

[[4 3 4]
 [2 4 3]
 [2 3 4]]
